_format_version: "1.1"
services:
  - url: https://www.digi-api.com/api/v1/digimon/
    routes:
      - paths:
          - "/digimon"
  - url: https://pokeapi.co/api/v2/pokemon/
    routes:
      - paths:
          - "/pokemon"
    plugins:
      - name: key-checker
        config:
          apikey: secretkeyandi
